- database/database.go
- database/gormdb.go
- models/course.go
- models/enrollment.go
- models/user.go
- web/courses.go
- web/courses_test.go
This is a work in progress to add a many-to-many relation between the user and course table with a status attribute. This PR will probably partially update/resolve #20, #21, #22, #23.
> Enrollment (WIP)

- public/src/components/student/SingleCourseOverview.tsx
- public/src/components/teacher/CourseGroup.tsx
- public/src/components/teacher/GroupResults.tsx
- public/src/components/teacher/Results.tsx
- public/src/managers/CourseManager.ts
- public/src/managers/ServerProvider.ts
- public/src/managers/TempDataProvider.ts
- public/src/models.ts
- public/src/pages/LoginPage.tsx
- public/src/pages/StudentPage.tsx
- public/src/pages/TeacherPage.tsx
- public/src/pages/views/MemberView.tsx
Autograde is now able to show a result set of group submissions to a teacher, and the submission results for students belonging to a group.
> Groupresults

- public/src/HttpStatusCode.tsx
- public/src/components/lab/LastBuildInfo.tsx
- public/src/components/lab/StudentLab.tsx
- public/src/components/student/CoursePanel.tsx
- public/src/components/teacher/GroupResults.tsx
- public/src/components/teacher/Results.tsx
- public/src/managers/CourseManager.ts
- public/src/managers/ServerProvider.ts
- public/src/managers/TempDataProvider.ts
- public/src/models.ts
- public/src/pages/StudentPage.tsx
- public/src/pages/TeacherPage.tsx
- public/src/pages/views/LabResultView.tsx
Instead of having to type out URLs manually and hoping that there are no typos, this suggests using constants and a URL building function.
Some TSLint improvement on the code too.
Also added a class for HTTP code constants, so we do not have to guess what the response code is.
> Urlbuilder

- scm/fake.go
- scm/github.go
- scm/gitlab.go
- scm/scm.go
- web/courses.go
- web/courses_test.go
- web/hooks.go
This branch makes it possible for the system to try and create private repositories and if it fails it will fall back to public repositories. A teacher may then after sorting payment click refresh course, and the system will loop through the repositories that are supposed to be private to become private.
> Privrepocreation

- database/database.go
- database/gormdb.go
- database/gormdb_test.go
- main.go
- models/repo.go
- public/src/managers/CourseManager.ts
- public/src/managers/ServerProvider.ts
- public/src/managers/TempDataProvider.ts
- public/src/pages/StudentPage.tsx
- web/courses.go
- web/groups.go
Branch that implements a way to enable the user to click on course information and be redirected to the corrospondig course-information git page.
Added a new coloumn in the repository table for html address, since url addresses will most likely not change that often, and will reduce the api calls to the git-providers.
Also improved the testing coverage for the gormDB implementation.
> Courseinformation

- database/database.go
- database/gormdb.go
- database/gormdb_assignm_test.go
- web/hooks.go
Fixed the implementation and added tests.
Fixed a bug in related code.
> moved GetNextUnapprovedAssignment to database package

- ci/scripts/go.tmpl
Updated rm pattern that would affect results of previously submitted labs
> updated go template

- ci/ci.go
- ci/docker.go
- ci/docker_test.go
- ci/local_unix.go
- ci/local_unix_test.go
- ci/local_windows.go
- ci/local_windows_test.go
- web/assignments.go
- web/assignments_parser_test.go
- web/hooks.go
- web/hooks_test.go
Every container running tests for a student submission will be tagged with the student's github username.
> Docker container tags

- public/src/pages/views/HelpView.tsx
Information about group creation is now presented on the application help page.
> Help page update

- public/src/components/lab/LastBuildInfo.tsx
- public/src/components/teacher/GroupResults.tsx
- public/src/components/teacher/Results.tsx
- public/src/managers/CourseManager.ts
- public/src/managers/ServerProvider.ts
- public/src/managers/TempDataProvider.ts
- public/src/pages/TeacherPage.tsx
Both button color and text, and "approved/not approved" text for student lab will now be correctly updated after successful approval of the lab.
Confirmation dialog is added when approving group labs.
> Approval of student/group labs

- web/users.go
- web/webserver.go
- shorter write timeout for http server
- closing the body of echo requests manually
> Attempt to fix "too many open files" error

- public/src/components/forms/GroupForm.tsx
- group form fields will be cleared after successful group edit/creation
- students added as group members will disappear from the list of available students
> Group form fix

- public/src/pages/StudentPage.tsx
Student page now has direct link to the group repository, along with other user and course repository links.
> Group repository link from student page

- public/src/pages/views/MemberView.tsx
- public/src/pages/views/UserView.tsx
Course members will be removed from pending list and added to the approved list when their course enrollments are approved.
> Updating user lists when approving student enrollments

- public/src/components/forms/GroupForm.tsx
- public/src/components/teacher/CourseGroup.tsx
- public/src/managers/UserManager.ts
- approve link will no longer show for already approved groups
- group list will refresh when new group is created by teacher
- group lists will refresh on group state changes
- approved groups can now be deleted
> Group-related updates and fixes

- public/src/components/lab/LabResult.tsx
- public/src/components/lab/LastBuildInfo.tsx
- public/src/components/lab/StudentLab.tsx
- public/src/components/student/CoursePanel.tsx
- public/src/components/teacher/GroupResults.tsx
- public/src/components/teacher/Results.tsx
- public/src/pages/StudentPage.tsx
- public/src/pages/views/LabResultView.tsx
- public/styles/style.css
> New lab result layout

- public/src/components/forms/CourseForm.tsx
- public/src/components/forms/GroupForm.tsx
- public/src/components/teacher/CourseGroup.tsx
- public/src/managers/CourseManager.ts
- public/src/managers/GRPCManager.ts
- public/src/managers/ServerProvider.ts
- public/src/managers/TempDataProvider.ts
- public/src/managers/UserManager.ts
- public/src/pages/StudentPage.tsx
- public/src/pages/TeacherPage.tsx
- more consistent order: courseID -> userID -> groupID
- names converted to proper camelCase
> Arguments to API methods

- public/src/components/bootstrap/BootstrapButton.tsx
- public/src/components/data/DynamicTable.tsx
- public/src/components/navigation/NavBar.tsx
- public/src/pages/StudentPage.tsx
- public/src/pages/TeacherPage.tsx
- public/src/pages/views/MemberView.tsx
- public/src/pages/views/UserView.tsx
- public/styles/style.css
- navigation bar always visible
- no empty `Settings` links
- striped tables
- two-button layout for lists with course members
- adjusted position for `Approve All` button
> UI updates

- ci/results.go
- public/src/components/lab/LabResult.tsx
- public/src/components/lab/LastBuildInfo.tsx
- public/src/components/student/CoursePanel.tsx
- public/src/components/student/SingleCourseOverview.tsx
- public/src/helper.ts
- public/src/pages/AdminPage.tsx
Submission build date had no information on the time of the submission build, while assignment deadline specifies the time. 
Now the time of the lab submission is also captured, stored in the database, and displayed along with other submission results information.
> Submission build date format

- public/src/components/teacher/CourseGroup.tsx
- public/src/components/teacher/Results.tsx
- public/src/components/teacher/groupHelper.tsx
- public/src/pages/TeacherPage.tsx
- all links leading to the course, student and group repositories will open in a new browser tab
- course repository links on the teacher page will no longer attempt to open a popup window
> Course repository links

- public/package-lock.json
- public/package.json
- public/src/components/navigation/CollapsableNavMenu.tsx
Fixes to make updated TS and webpack compatible with codebase and each other.
> Front-end dependencies

- public/package-lock.json
- public/package.json
- public/src/components/navigation/CollapsableNavMenu.tsx
- public/src/pages/views/MemberView.tsx
- public/src/pages/views/UserView.tsx
Changes to MemberView:
- new Edit mode button
- new Role status buttons displayed in normal mode
- action buttons only displayed in Edit mode
> MemberView updates

- database/gormdb.go
- doc/dev.md
- scm/github.go
- scm/helper.go
- web/access_control.go
- web/assignments_test.go
- web/autograder_service.go
- web/courses.go
- web/courses_new.go
- web/courses_test.go
- web/scm_helpers.go
- return specific error message to be shown to user if github cancels request context
- return more detailed error messages to teachers when methods fail because of github interactions
> Scm errors

- database/gormdb.go
- database/gormdb_assignm_test.go
Fix for new submissions not being updated correctly in the database.
> submission update fix

- public/src/components/forms/CourseForm.tsx
- scm/github.go
- web/courses_new.go
- web/scm_helpers.go
- a student `-labs` repo will be added for the course creator
- when creating a new course, a direct link to the organization third party access page will be displayed to the user when the organization cannot be found by name
> Course creation updates

- scm/github.go
- web/access_control.go
- web/autograder_service.go
- web/bh.go
- web/courses.go
- web/courses_test.go
- web/users.go
Any course teacher can now freely promote and demote other course teachers. The course creator can never be demoted.
> Teacher status change restrictions

- public/src/components/bootstrap/BootstrapButton.tsx
- public/src/components/bootstrap/Dropdown.tsx
- public/src/components/data/DynamicTable.tsx
- public/src/components/navigation/NavBarLogin.tsx
- public/src/components/teacher/CourseGroup.tsx
- public/src/components/teacher/GroupResults.tsx
- public/src/components/teacher/Results.tsx
- public/src/managers/NavigationManager.ts
- public/src/pages/views/LabResultView.tsx
- public/src/pages/views/MemberView.tsx
- public/src/pages/views/UserView.tsx
- public/styles/style.css
- `DynamicTable` and `BootstrapButton` classes now allow custom class names
- table columns in group and user lists are now aligned
- actions in group list are now displayed as buttons, instead of a dropdown menu
> Changes to lists of course users and groups

- assignments/assignments_test.go
- scm/fake.go
- scm/github.go
- scm/github_test.go
- scm/gitlab.go
- scm/helper.go
- scm/scm.go
- web/courses.go
- web/courses_new.go
- web/scm_helpers.go
Minimizing calls to GitHub, updating `fake` provider, removing and rewriting outdated methods and structs.
> Scm package updates

- public/src/components/forms/GroupForm.tsx
- public/src/components/teacher/CourseGroup.tsx
- public/src/managers/CourseManager.ts
- public/src/managers/ServerProvider.ts
- public/src/managers/TempDataProvider.ts
- public/src/pages/views/MemberView.tsx
- scm/github.go
- web/autograder_service.go
- web/groups.go
When changing enrollment status, approving, editing or deleting groups fails, there were no error messages shown to the user.
> Error messages for group and member view

- ag/validation.go
- public/src/components/data/DynamicTable.tsx
- public/src/components/forms/GroupForm.tsx
- public/src/components/student/CoursesOverview.tsx
- public/src/components/teacher/CourseGroup.tsx
- public/src/components/teacher/GroupResults.tsx
- public/src/components/teacher/Results.tsx
- public/src/managers/CourseManager.ts
- public/src/managers/GRPCManager.ts
- public/src/managers/UserManager.ts
- public/src/pages/StudentPage.tsx
- public/src/pages/TeacherPage.tsx
- public/src/pages/views/EnrollmentView.tsx
- public/src/pages/views/UserView.tsx
The student page stopped showing course labs because of a missing check. Here is a fix for this issue.
> Studentpage fix.

- Makefile
- public/package-lock.json
- public/package.json
- web/submissions_test.go
- updated deeper front-end dependencies, latest webpack version
- updated Makefile
- new test for previously uncovered gRPC method, with additional checks that new assignments land in the database for correct courses, and new submissions are being saved for correct assignments
> Deps and tests

- public/package-lock.json
- public/package.json
- public/src/components/teacher/CourseGroup.tsx
- public/src/managers/CourseManager.ts
- public/src/managers/GRPCManager.ts
- public/src/managers/ServerProvider.ts
- public/src/managers/TempDataProvider.ts
- public/src/pages/StudentPage.tsx
- public/src/pages/TeacherPage.tsx
- public/src/pages/views/MemberView.tsx
This PR addresses three issues:
- when promoting to teacher/demoting a teacher resulted in error, the status of the user would still be changed locally;
- when approving a new group it would be temporarily marked as approved even if the method failed;
- when approving or rejecting a user enrollment, lists of the approved and pending students would not be updated without a manual page reload.
> Fixing MemberView

- public/src/components/forms/GroupForm.tsx
- public/src/managers/CourseManager.ts
- public/src/models.ts
- public/src/pages/AdminPage.tsx
- public/src/pages/TeacherPage.tsx
- public/src/pages/views/MemberView.tsx
- public/src/pages/views/UserView.tsx
- replaced `IUserRelation` model with `Enrollment`
> Replacing models with protobuf-defined types

- Makefile
Trying to stop Prometheus data loss.
> updated options to start prometheus server

- Makefile
An attempt to make it possible running the server with full functionality (including authentication with GitHub) locally, without port forwarding.
> Testing on localhost

- ci/docker.go
- ci/run_tests.go
- database/gormdb_assignment.go
- public/src/components/teacher/GroupResults.tsx
> Minor fixes

- public/src/managers/ServerProvider.ts
This was not previously pushed to master. Saving it here for the record. If this is correct, we should just merge into master.
> Fix in ServerProvider.ts from ag3

- ag/assignments.go
- web/courses.go
- web/discord_test.go
> Lab results optimization

- public/src/components/lab/LabResult.tsx
- public/src/components/lab/LastBuild.tsx
- public/src/components/manual-grading/Release.tsx
- public/src/components/manual-grading/Review.tsx
- public/src/components/progressbar/ProgressBar.tsx
- public/src/components/student/CoursePanel.tsx
- public/src/components/student/SingleCourseOverview.tsx
- public/src/components/teacher/GroupResults.tsx
- public/src/components/teacher/Results.tsx
- public/src/pages/views/LabResultView.tsx
- public/styles/style.css
The submission progress bar will now display remaining percents to reach the passing level, turn green if the passing level has been reached.
Resolves #313.
> More informative progress bar

- public/src/components/lab/LastBuild.tsx
- public/src/components/teacher/GroupResults.tsx
- public/src/components/teacher/Results.tsx
- removed "pts" line showing for tests with zero weight
- added non-breakable space to percent signs
> Lab results UI fixes

- .vscode/settings.json
- ag/repo.go
- ag/repo_test.go
- ci/parse_script.go
- ci/parse_script_test.go
- ci/run_tests.go
- ci/run_tests_test.go
- web/hooks/github.go
- web/rebuild.go
- web/repositories.go
- some assignment info and url clean up
- minor log fix
> assignment info url

- public/src/componentHelper.tsx
- public/src/pages/TeacherPage.tsx
- web/courses.go
Fixes a bug where pending students sometimes would not show in the course member list.
> Fix for pending students in member lists

- database/gormdb_submission.go
This method is already used in the expected way, so there is no
need to create another pb.Submission object.
The tests still pass.
> Minor simplification of db.GetSubmissions

- ci/run_tests_test.go
- ci/scripts/go.sh
- ci/scripts/go/Dockerfile
- kit/score/score.go
- kit/score/score_test.go
> Remove global secret variable and use environment variable instead

- public/src/components/forms/UserProfile.tsx
- public/src/index.tsx
Removes user references from the page state to prevent unauthorized access.
> Fix access bug

- .github/workflows/golangci-lint.yml
- .vscode/settings.json
- README.md
Fixes #388. Most fixes have already been applied to master directly.
> Added golangci-lint workflow and badge

- public/src/managers/GRPCManager.ts
- public/src/managers/ServerProvider.ts
- public/src/pages/TeacherPage.tsx
> Fix issue with TAs having unintended teacher view access to other courses

- public/src/componentHelper.tsx
- public/src/components/manual-grading/EditCriterion.tsx
- public/src/components/manual-grading/Release.tsx
- public/src/components/manual-grading/Review.tsx
- public/styles/style.css
- web/assignments.go
- number of reviews can no longer be higher than maximum set in the assignment.yaml
- fixed incorrect score calculation for submission with too many reviews
- fixed incorrect score calculation for reviews with custom number of points
- fixed wrong score displayed in the header
- fixed incorrect alignment of custom points information
- fixed links to student repositories
- fixed summary feedback not being displayed properly
Resolves #398.
> Fix for review score issues

- database/gormdb_submission.go
Adjustments to updating previously set score for a submission to zero.
> Update submission score to zero

- public/src/index.tsx
The event logged to console include references to all managers.
> Removed an event listener in index.tsx

- go.mod
- go.sum
- scm/github.go
- web/hooks/github.go
Should be tested properly before merging. (the tests in github_test.go is not performed yet)
Closes #436
> go-github v30/v32 -> v35

- .vscode/settings.json
- doc/dev.md
- public/package-lock.json
- public/package.json
- public/src/helper.ts
- public/src/pages/views/ReleaseView.tsx
- public/webpack.config.js
This also fixes a recent dependabot security issue in set-getter.
> Updated npm and various typescript issues

- ag/assignment.go
- ag/assignment_test.go
- ci/run_tests.go
This makes use of the existing IsApproved method to simplify code in recordResults.
> Use existing IsApproved method; now with tests

- assignments/assignments.go
- database/gormdb_submission.go
- database/gormdb_submission_test.go
> Fixing scores not updating properly when a submission updates

- ci/run_tests.go
If the user tries to rebuild a submission whose newst submission
hasn't been recorded in the database, e.g., due to a failure or
bug in quickfeed, the newest submission's BuildInfo will be nil.
This caused a panic and crash of the server.
> Hotfix: Allow rebuild without previous submission from database

- scm/github.go
- web/scm_helpers.go
- Improved logging for CreateRepository
- Improved logging for CreateTeam
- Removed useless GetRepo check and logging
- Removed allocation and added context to error msg
Fixes #511
> Fix confusing log messages during user/repo creation

- web/rebuild.go
- web/rebuild_test.go
> Fix same submission being queued multiple times for rebuild

- .gitignore
- cmd/approvelist/main.go
- go.mod
- go.sum
- web/autograder_service.go
Rename qctrl to approvelist and updated to use auth meta data to access the server following same principle as helpbot. This is a temporary hack.
> Update approvelist command

- ag/slipdays_test.go
- assignments/assignments_parser_test.go
- ci/run_tests_test.go
- cmd/approvelist/main.go
- database/db_user_test.go
- database/gormdb.go
- database/gormdb_assignment_test.go
- database/gormdb_course.go
- database/gormdb_group_test.go
- database/gormdb_submission_test.go
- database/gormdb_test.go
- database/gormdb_user_test.go
- internal/qtest/test_helper.go
- web/courses_test.go
- web/groups_test.go
- web/grpc_auth_test.go
- web/users_test.go
- Replace cmpopts.IgnoreUnexported with protocmp.Transform
Fixes #465
> Replace cmpopts.IgnoreUnexported with protocmp.Transform

- kit/score/doc.go
> Fix indent in kit/score godoc

- .github/workflows/coverage.yml
- .github/workflows/go.yml
- .github/workflows/golangci-lint.yml
- .vscode/extensions.json
- .vscode/settings.json
This updates the workflow files for github actions to newest version for all actions.
> Updated workflows for github actions

- .github/workflows/jest.yml
- jest tests and configuraton
- code review comments
- email test
- Fixed formatting of tests
- Added words to cspell
- Cleanup jest_testing.md
- Moved jest-testing.md to doc folder
- Updated node_modules/minimist dependency to v1.2.6
- deepsource and gitignore
- javascript deepsource fixes
- moved generateSubmissionRows and generateAssigmentsRow
- deepsource comments
- Regenerated proto for frontends and updated one dependency
- Updated grpc-web to 1.3.1 also in package.json
- jest yml file
> github workflow for jest tests

- .vscode/quickfeed-words.txt
- .vscode/settings.json
- Makefile
- README.md
- cmd/vercheck/main.go
- Added proto_path options to settings.json
- Added grpcweb version check before the ui target
- Added check for latest release version of grpc-web
- Added alternative install instructions for grpc-web
Fixes #629
> Adds version check for grpc-web

- cmd/envoy/envoy_config_gen.go
> Fix for poor file permissions in envoy_config_gen

- assignments/assignments.go
- ci/parse_script.go
Fixed issue where Docker requires lowercase image names.
Resolves #717
> Lowercase docker image names

- .vscode/quickfeed-words.txt
- ci/docker.go
- ci/docker_test.go
- ci/parse_script.go
- ci/parse_script_test.go
- ci/run_tests_test.go
- ci/testdata/Dockerfile
- ci/testdata/tests/x_test.go
> Fix to allow docker to run as non-root

- .vscode/quickfeed-words.txt
- scm/github_test.go
> Improve TestRequestReviewers

- assignments/pull_requests_test.go
- scm/github_test.go
> Fixed TestFeedbackCommentFormat to genereate score results in the PR as a comment

- database/db_user_test.go
- qf/user.go
- scm/fake.go
- scm/github.go
- scm/github_app.go
- scm/github_invite.go
- scm/gitlab.go
- scm/scm.go
- scm/scm_invite.go
- web/auth/auth.go
- web/courses.go
- web/courses_test.go
- web/groups_test.go
- web/scm_helpers.go
- Fixed accepting repository invites
- Store refresh token, and exchange for access token
> Exchange Refresh Token for Access Token

- go.mod
- web/assignments.go
- web/courses.go
- web/groups.go
- web/quickfeed_service.go
- web/users.go
Removes several (now) useless and trivial getters called from quickfeed_service.go.
Fixes #733
> Remove simple getters

- .github/workflows/golangci-lint.yml
- .vscode/quickfeed-words.txt
- assignments/assignments_test.go
- ci/docker.go
- ci/docker_test.go
- internal/multierr/multierr.go
- internal/multierr/multierr_test.go
- internal/qtest/test_helper.go
- main.go
- scm/test_helper.go
- web/hooks/pull_request.go
> Add missing error checks

- database/gormdb_course.go
- database/gormdb_enrollment.go
- qf/course.go
- qf/enrollment.go
- qf/group.go
- qf/user.go
- web/courses.go
- web/groups.go
- web/quickfeed_service.go
> Fixed an issue where remaining slipdays would not reach the frontend

- web/auth/consts.go
- web/auth/jwt.go
- web/interceptor/access_control.go
- web/interceptor/access_control_test.go
- web/interceptor/tokens.go
- web/interceptor/user_auth.go
- Added user verifier interceptor & `wantCode` field to test structs
- Added helper to set/get claims as/from context value
- Added claims to context in interceptors
> Pass Claims in Context

- public/.env-template
- public/package-lock.json
- public/package.json
- public/src/components/admin/CourseCreationInfo.tsx
- public/webpack.config.js
- Added `dotenv` to Webpack to allow injecting values
- Hardcoded URLs are now fetched from process.env
> Hardcoded URLs now passed from .env file

- kit/score/results_test.go
> Adds tests for multiple zero score objects

- scm/mock.go
- scm/mock_test.go
- web/courses_test.go
> Adding tests for Mock SCM methods.

- web/quickfeed_service.go
- web/scm_helpers.go
> Update handling of context errors.

- ci/clone_repositories.go
- ci/parse_script.go
- ci/parse_script_test.go
- ci/run_tests.go
- ci/run_tests_clone_test.go
- cmd/qcm/main.go
- qf/repo.go
- scm/github_invite.go
- scm/mock_test.go
- web/courses_new.go
- web/hooks/push.go
- web/quickfeed_service.go
- web/scm_helpers.go
> Fixed cloning of tests and assignments repos if missing

- ci/run_tests_test.go
- cmd/scm/main.go
- scm/fetcher_test.go
- scm/github.go
- scm/mock.go
- scm/scm.go
Resolves #827, fixes #828, resolves #829.
> Removing unused scm methods for usernames and clone urls. 

- qf/repo.go
- web/hooks/push.go
Resolves #803.
Adding relevant tests in a separate PR.
> Update webhook push event handler.

- doc/doc-urls.go
- internal/env/env_test.go
- internal/env/save.go
- main.go
- web/manifest/manifest.go
Fixes #825.
Note this builds on #820.
> Fixes failure during github app creation due to existing .env.bak file

- scm/github_invite.go
- scm/helper.go
- scm/mock.go
- scm/scm.go
- scm/scm_invite.go
- web/auth/github.go
- web/courses.go
- web/scm_helpers.go
> Added method to accept a organization invite on behalf of a user

- .github/workflows/coverage.yml
- .github/workflows/go.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/jest.yml
- .vscode/quickfeed-words.txt
- README.md
Updating GitHub actions to latest versions.
> Update GitHub actions

- ci/docker.go
- ci/docker_test.go
> Fix docker pull from non-Docker hub repositories

- web/courses_test.go
- web/groups.go
- web/groups_name_test.go
- web/interceptor/access_control_test.go
- web/interceptor/tokens_test.go
- web/interceptor/user_auth_test.go
- web/quickfeed_helper_test.go
- web/quickfeed_helper_web.go
- web/quickfeed_service.go
- web/thirdparty_auth_test.go
- web/users_test.go
- Fixed MockClient to use a httptest.Server
- Moved the bad group name test to web_test package
Partial fix for #791.
> Move TestBadGroupNames to web_test package

- scm/github.go
- scm/helper.go
I screwed up. Just to merge into master...
> Remove scm err

- public/src/components/ReviewResult.tsx
- public/src/components/manual-grading/MarkReadyButton.tsx
- public/src/components/manual-grading/ReviewInfo.tsx
> Add mark as ready button at the end of a review

- database/database.go
- database/gormdb_assignment.go
- database/gormdb_assignment_test.go
- database/gormdb_tasks.go
- database/gormdb_tasks_test.go
- qf/submission_request.go
- qf/submission_request_test.go
- web/assignments.go
- web/courses.go
Helpers that can be useful in some database calls and elsewhere.
> SubmissionRequest helpers IncludeAll() and Include(Assignment)

- web/access_control.go
- web/auth/consts.go
- web/auth/jwt.go
- web/groups_name_test.go
- web/interceptor/user_auth.go
- web/rebuild_test.go
- web/users_test.go
> Remove WithUserContext

- scm/helper.go
- scm/scm_manager.go
- web/hooks/push.go
- web/quickfeed_service.go
> Fix GetOrCreateSCM

- Makefile
> Added sudo setcap for make install target on linux

- public/src/components/group/GroupForm.tsx
> Fixed GroupForm bug

- public/index.tmpl.html
- public/package-lock.json
- public/package.json
- public/src/components/UnstyledButton.tsx
- public/src/components/manual-grading/Comment.tsx
- public/src/components/manual-grading/Criterion.tsx
- public/src/components/manual-grading/GradeComment.tsx
- public/src/components/manual-grading/SummaryFeedback.tsx
- public/src/style.scss
- public/webpack.config.js
> Add support for writing markdown comments

- public/.eslintrc.json
- public/package-lock.json
- public/package.json
- public/src/Helpers.ts
- public/src/__tests__/updateEnrollment.test.tsx
- public/src/components/Courses.tsx
- public/src/components/DynamicButton.tsx
- public/src/components/Groups.tsx
- public/src/components/ManageSubmissionStatus.tsx
- public/src/components/Members.tsx
- public/src/components/Release.tsx
- public/src/components/Results.tsx
- public/src/components/admin/Button.tsx
- public/src/components/admin/Users.tsx
- public/src/components/forms/TableSort.tsx
- public/src/components/group/GroupForm.tsx
- public/src/components/manual-grading/MarkReadyButton.tsx
- public/src/components/manual-grading/ReviewForm.tsx
- public/src/components/manual-grading/ReviewInfo.tsx
- public/src/components/teacher/Assignments.tsx
- public/src/overmind/actions.tsx
- public/src/overmind/namespaces/review/actions.ts
- public/src/overmind/state.tsx
This PR improves areas of the frontend where the user experience / user interface is currently lacking.
- Added spinners to relevant buttons for visual feedback during server requests.
- Converted `span` and `div` elements masquerading as buttons into actual button elements for better accessibility and keyboard focusability.
- Fixed bugs related to server response delays, preventing incorrect overwriting of data in state and multiple identical requests in progress.
- Fixed bugs where state would become corrupted (incorrectly updated) when navigating while a server request is in progress
- Fixed an issue with releasing submissions not being reflected in the review table; the state now updates and components re-render correctly.
- Re-enabled the `Release` component.
- The name of the …
> Enhance frontend UX/UI: button feedback, accessibility, and bug fixes in state, Review and Results views

- public/src/Helpers.ts
- public/src/__tests__/validateGroup.test.ts
- public/src/overmind/actions.tsx
- public/src/overmind/state.tsx
This PR adds client-side validation for group creation. The validation ensures that the group name meets the required format, and that the group is not empty.
If the validation fails, an alert is displayed to the user, indicating the specific error that occurred. The server also performs the same validation, so the client-side validation serves as an additional layer of protection and helps to improve the overall user experience by preventing unnecessary server requests.
> Group creation validation

- .github/workflows/coverage.yml
- .github/workflows/go.yml
- .github/workflows/golangci-lint.yml
- assignments/assignments_parser.go
- assignments/assignments_parser_test.go
- database/gormdb_assignment.go
- go.mod
This should produce error log if the order field wasn't initialized in the assignment.yml file.
Fixes #999
> Check for uninitialized order field

- ci/testdata/run.sh
- doc/templates/go-course/scripts/run.sh
- testdata/courses/qf104-2022/tests/lab2/sequence/run.sh
- testdata/courses/qf104-2022/tests/scripts/run.sh
> Fix bug in run.sh script template files

- kit/sh/cmd.go
- kit/sh/cmd_test.go
- kit/sh/race_test.go
- quickfeed.code-workspace
> feat(kit): add sh.RunRaceTest for running tests with race detector

- public/src/components/navbar/NavBarActiveCourse.tsx
- public/src/components/navbar/ToggleSwitch.tsx
- fix: student/teacher toggle visuals not updatig correctly when toggling
- fix: navigate to course top level on student/teacher toggle
> Improvements for the student/teacher toggle switch

- qf/requests.proto
> Removes old Void comment no longer relevant

- assignments/assignments_parser_test.go
- database/gormdb_course_test.go
- web/courses_test.go
- web/groups_test.go
- web/interceptor/access_control_test.go
- web/rebuild_test.go
- web/submissions_test.go
- web/users_test.go
> Replace db.CreateCourse with qtest.CreateCourse all over

- public/src/components/admin/CreateCourse.tsx
- public/src/components/forms/CourseForm.tsx
- public/src/components/navbar/NavBarCourse.tsx
- **fix: use courses from state for sidebar rather than courses nested under enrollment**
- **fix: button in course form now says "Save" rather than "Edit Course"**
- **fix: improve error message for course not found**
closes #1129
> ui: minor fixes related to course create/edit

- public/src/components/navbar/NavBarTeacher.tsx
- public/src/overmind/state.tsx
> feat: add indicator for pending/approved groups in sidebar menu

- public/src/components/CourseCard.tsx
Card header contents is now properly aligned vertically
Semester / year is now on a separate line
Added some shade to the box
Closes #1135
> ui: improved course card visuals

- public/package.json
- public/src/Helpers.ts
- public/src/__tests__/lab.test.tsx
- public/src/__tests__/mock_data/mockData.ts
- public/tsconfig.json
> Fix lab view not re-rendering properly when submission updates

- ci/run_tests_test.go
- internal/qtest/test_helper.go
> DeepSource, resolve: Function with cyclomatic complexity higher than threshold GO-R1005 (run_tests_test.go)

- ci/parse_script_test.go
- ci/run_tests.go
- qf/submission_test.go
- scm/github_mock.go
- scm/github_mock_opts.go
> DeepSource: Resolve 4 Go issues. 19 occurrences in total

- public/src/components/DynamicTable.tsx
- public/src/components/admin/User.tsx
- public/src/components/alerts/Alert.tsx
- public/src/components/forms/TableSort.tsx
- public/src/components/manual-grading/GradeComment.tsx
- public/src/components/navbar/NavBarCourse.tsx
- public/src/components/navbar/NavBarLabs.tsx
- public/src/components/navbar/NavBarLink.tsx
- public/src/components/student/SubmissionRow.tsx
- public/src/components/teacher/Assignments.tsx
- public/src/pages/AboutPage.tsx
Closes #1245 
This should not disrupt any visual layout, I think. Its very hard to determine where the different elements end up, but I only fixed the issues noticed, refering to [chore(NavBarCourse.tsx): Nest li inside div instead](https://github.com/quickfeed/quickfeed/commit/2807b84a652db974fa3f1bd2c34ad8c9bc9ad0ec) and NavBarLink see below.
Im pretty everything looks the same, I solved some problems with adding a new div, especially for NavBarLink. DeepSource apparently doesn't complain if you just remove the role "button" on the li element....
> DeepSource(Frontend): Resolve 6 issues with 23 occurences in total

- public/src/components/teacher/RoleSwitch.tsx
> Fix: Can't compile frontend

- public/.eslintrc.json
- public/src/components/student/AssignmentCard.tsx
- public/src/components/student/SubmissionRow.tsx
- public/src/style.scss
> Expand onclick area for assignment cards and add hover effect

- public/.eslintrc.json
- public/src/components/teacher/EditBenchmark.tsx
- public/src/components/teacher/EditCriterion.tsx
- public/src/overmind/actions.tsx
> Fix create, edit and delete issues for both Benchmark and Criterion

- public/src/Helpers.ts
- public/src/__tests__/lab.test.tsx
- public/src/components/CenteredMessage.tsx
- public/src/components/Lab.tsx
- public/src/components/LabResult.tsx
- public/src/components/ManageSubmissionStatus.tsx
- public/src/components/Results.tsx
- public/src/components/ReviewResult.tsx
- public/src/components/manual-grading/ReviewForm.tsx
- public/src/components/manual-grading/ReviewInfo.tsx
- public/src/components/navbar/NavBarTeacher.tsx
- public/src/components/submissions/SubmissionInfo.tsx
- public/src/components/teacher/Assignments.tsx
- public/src/overmind/actions.tsx
- public/src/overmind/state.tsx
- public/src/pages/TeacherPage.tsx
> Hide ManageSubmissionStatus (approve,revision,reject) when an assignment or submission isn't seleted

- public/src/components/navbar/NavBarLabs.tsx
> Use submission ID instead of assignment ID to prevent duplicate keys for elements (react issue)

- .vscode/quickfeed-words.txt
- web/quickfeed_service.go
- web/scm_helpers.go
- web/scm_helpers_test.go
> Simplify and rename parseSCMError to userSCMerror

- .env-template
- internal/env/scm.go
- internal/ui/esbuild.go
- public/.env-template
- public/src/components/admin/CourseCreationInfo.tsx
> Esbuild: Load the App Url and add key: process.env.QUICKFEED_APP_URL to Define map in build options

- public/src/components/navbar/NavBarLabs.tsx
- public/src/components/navbar/NavBarLink.tsx
- public/src/components/navbar/NavBarTeacher.tsx
> Refactor NavLink: Remove child object link and adjust props input of NavbarLink component

- internal/ui/esbuild.go
- internal/ui/esbuild_test.go
- web/manifest/manifest.go
- web/manifest/manifest_internal_test.go
> Update Esbuild output dir documentation and related tests, and adjust npm ci public path

- Makefile
> Add npm run test to the test makefile target

- public/src/components/navbar/NavBarActiveCourse.tsx
> Remove unnecessary visibility of NavbarActiveCourse when user is at the Dashboard

- public/src/components/Members.tsx
Closes: #1368
I debated on creating a test for the members component. To avoid regression, but it appears to be complex and fragile. Any further changes made to member.tsx will require updates in the test.
> Fix previous slip up in members.tsx

- public/src/components/ReviewResult.tsx
- public/src/components/manual-grading/GradeAllCriteria.tsx
- public/src/overmind/namespaces/review/actions.ts
- **fix: ensure MarkReadyButton is only shown to teachers when review is not ready**
- **feat: add GradeAllCriteria component to set grades for all criteria**
- **feat: add GradeAllCriteria component to allow teachers to set grades for all criteria**
> feat: add functionality to grade all criteria

- database/gormdb_review_test.go
Prior to 4b555c3 we would have to update a review twice to persist a change to a criterion.
The added test verifies that this is fixed (when run on commit prior to 4b555c3 this test fails).
> test: add TestCreateUpdateReview to validate review creation and updates
