quickfeed/quickfeed

database/gormdb.go
database/gormdb_test.go
web/courses.go
web/courses_test.go

Background: It is becoming apparent that teachers may already have created one or more repositories for autograder manually on their organization. 
This commit adds support for detecting if a course was already created in the database for some directoryID (e.g. github organization).
It also allows repo creation to fail and continue and thus create hooks for existing repos. This is useful if a teacher already created one or more of the repos, yet have the necessary hooks established for the course.
PS: Currently, the frontend does not tell the user that the course creation failed. This should be fixed.

web/courses.go,database/gormdb.go: detection of duplicate course creation

---

database/database.go
database/gormdb.go
database/gormdb_assignm_test.go
database/gormdb_test.go
web/courses.go
web/courses_test.go
web/groups_test.go
web/users_test.go

This change makes it explicit who is the course creator by
checking that the user is admin and should be allowed to create
the course. Further, the user is then enrolled in the course
as teacher.
This change impacted a lot of tests, but almost no business logic.
It basically only changes web/courses.go by moving the enrollment
logic into the database.CreateCourse() method, since this should
actually be done in one transaction, so that if the user couldn't
be enrolled as teacher, the course won't created either.
Currently, the implementation does not support transactions, but
it should be easy to do with GORM at a later time, if necessary.
All the other changes are mostly related to adapting to the new
semantics of CreateCourse(), but there are also some simplifications
to some of the …

refactored database.CreateCourse() to take course creator (user)

---

public/src/components/navigation/NavBar.tsx
public/src/components/navigation/NavHeaderBar.tsx

The toggle-navbar button on frontend didn't cause the dropdown to appear.
This makes the button operational!
Note: Had to make an unrelated commit 3ef4f6f to make webpack compile 😕

Fix toggle-navbar button for mobile

---

ag/repo.go
public/src/components/forms/CourseForm.tsx
public/src/components/lab/LabResult.tsx
public/src/pages/TeacherPage.tsx
public/src/pages/views/LabResultView.tsx
web/hooks.go
web/rebuild.go

Previously approved labs would be marked as unapproved if rebuild of that lab was triggered by push event. Both push event and rebuild button event will now ignore already approved labs.

Fix for rebuilding of approved labs

---

ci/docker.go

Docker container timeout is not compatible with the older Docker API. Removed it from the code

disabled docker container timeout

---

web/autograder_service.go
web/submissions_test.go

When accessing group submissions, there will no longer be enough to provide any group ID > 0, the current user must also be a group member (or course teacher).

Group submission access

---

public/src/pages/StudentPage.tsx
public/src/pages/TeacherPage.tsx

- the link leading to the group form (used to create a new group) has been renamed: was `Members`, now `New Group`
- the same link has been added to the teacher page links

Link to the group creation page from the teacher page

---

database/database.go
database/gormdb.go
database/gormdb_test.go
web/access_control.go
web/autograder_service.go
web/courses.go
web/groups.go
web/hooks.go

- `GetUserAndSCM2` is now `GetUserAndSCMForCourse`
- gorm methods `GetRepository` and `DeleteRepository` are now `GetRepostoryByRemoteID` and `DeleteRepositoryByRemoteID` correspondingly, to reflect the expected ID type

Methods rename

---

scm/github.go
web/groups.go
web/groups_test.go

Previously, methods that use github API would sometimes fail due to context cancelling. That would result in group or student repository created correctly on the github, but no corresponding entries created in the database. Because of that, enrolling such user or approving such group would become impossible, as corresponding methods would fail, and github repositories had to be manually removed.
Now an already existing github repository will be correctly reflected in the database on the next attempt to enroll the student or approve the group.

Group updates

---

envoy/envoy.yaml

Envoy configuration field `allow_origin` has been deprecated. Because of that building a new envoy container based on the old `.yaml` file. became impossible. New field name is `allow_origin_string_match`.
Note: `regex` option for the `allow_origin_string_match` field is also deprecated, use `safe_regex` instead if needed.

updated deprecated fields in envoy config

---

go.mod
public/src/components/forms/GroupForm.tsx
scm/github.go
web/autograder_service.go
web/groups.go
web/scm_helpers.go

Sometimes a new group could not be approved because of canceled context on GitHub side. This way, repository or team for the group might have been created on GitHub, but nothing would be reflected in the database. As a result, approving such a group would become impossible because of GitHub and database mismatch.
This fix introduces following changes:
- two groups with names that would result in the same github repository name can no longer be created
- issue when some students could not create a new group with "not in group" error message is now fixed
- if a group repository or team already have been created on GitHub, this information will be updated in the database instead of failing the request
- a group that could not be approved due to GitHub related issues now can be approved later …

Approving a new group fix

---

cmd/agctl/main.go
database/database.go
database/gormdb.go
database/gormdb_test.go
public/src/HttpHelper.ts
public/src/components/teacher/Results.tsx
public/src/managers/GRPCManager.ts
public/src/managers/ServerProvider.ts
public/src/managers/UserManager.ts
public/src/pages/AdminPage.tsx
web/groups_test.go
web/submissions_test.go
web/users.go
web/users_test.go

Admins (unless super admin) can now be demoted. This will resolve the issue where students previously granted admin role as TAs could have admin access to other courses.

Demote admins

---

database/gormdb.go

Database method `CreateUserFromRemoteIdentity` was expecting an old `UpdateUser` method behavior. Now fixed.

fixed bug when creating user from remote ID

---

assignments/assignments_parser.go
assignments/assignments_parser_test.go
web/access_control.go
web/assignments.go
web/courses.go

To avoid possible mismatches between assignment name provided in the `assignment.yaml` file, and the actual assignment folder name (must be identical, but no way to enforce it), name the assignment by its folder. 
This will make the `Name` field in the yml files unnecessary.

Set assignment folder name as assignment name

---

web/groups.go

Previously the name of a new group was only checked against the approved groups. Now the check will also include pending groups.

Preventing group name collision

---

web/hooks/github.go

The current `extractAssignment` function only examines the `commit.Modified` field. This doesn't capture commits that only rename/add/remove files. This commit fixes that by also examining the `commit.Added` and `commit.Removed` fields in order to extract the labX name.

fixed extractAssignment to also recognize commits with added/removed files

---

web/hooks/github.go
web/hooks/github_test.go

This commit fixes a bug that was triggered when students push
changes that touch root-level files, that don't belong to any
assignments, e.g. go.mod or README.md and so forth.
The commit also includes a test case for the function that
process the data coming from github.
Note: it is sometimes easy to forget to return or continue when
processing an error. Should be on the lookout for such mistakes.

fix bug in processing of assignment strings from github

---

kit/exercise/command_line.go

Some applications (e.g. golangci-lint) send the output to stdout
rather than stderr on an "error". In such cases it's desirable to
compare the error output with the expected output.
This fix uses the contents of stdout to determine if the test failed
in the case stdout has any content.

check if stdout is empty before continuing on error

---

kit/exercise/command_line.go
kit/exercise/command_line_test.go

Motivation: The output from the CommandLine function is minimal in
some cases. E.g. in our use-case we wanted to detect a data race by
running `go test -race ...` with the CommandLine function and looking
for "DATA RACE" in the output. However we were unable to show the full
output (stack trace etc.) related to the data race when it was found.
With this update the output to stdout and stderr along with any error
from exec.Command are returned as slices, one for each command that
is run. As a result, callers of CommandLine can investigate the
results and use them as they please when some error occurs. Since
there were no return values before, this change should not conflict
with existing code.
I was not sure about introducing new types, but you might also
consider a "CommandLineError" type …

Return stdout, stderr, error from func CommandLine

---

web/hooks/github.go

Removed a line that made logger print out every commit made by the student to their lab repository on every new push to that repository.

Reducing noise in the server logs

---

database/gormdb_assignment.go
public/src/managers/CourseManager.ts
public/src/pages/TeacherPage.tsx

Fixes the issue where `Results` table had assignments in the table header sorted by the Assignment's field `Order`, while submissions in the table body were sorted by the Assignment's database ID, which could cause a bug where submissions in the table column were displayed for a wrong assignment.

Order lab submissions by assignment's order

---

ci/results.go
ci/results_test.go
go.mod
go.sum
kit/.vscode/settings.json
kit/exercise/command_line_test.go
kit/exercise/multiple_choice.go
kit/exercise/multiple_choice_test.go
kit/go.mod
kit/go.sum
kit/score/score.go
kit/score/score_test.go
kit/score/totalscore_test.go

This commit fixes #315.
This commit updates the score package in kit module to always
write an initial Score JSON to StdOut. This prevents test score
values from getting lost when students do something wrong which
causes the test execution to panic.
This change implies that Quickfeed must filter the Score JSON
strings found in the results log so that only one Score is
returned and used in the calculation of the Total.
When filtering, we assume only one or two Score strings;
if only one is found, it means that it is the one initialized
by the NewScore* constructor, and it is used, giving only 0 score;
if two is found, only the last one is used, meaning that the
score is the result of running some tests;
if more than two are found, something is amiss and we return
a 0 score object.
This …

emit 0 score JSON at start and updated with a non-zero score JSON

---

ci/docker.go
ci/docker_test.go

This commit fixes #319.
The problem was that we only stopped the container, but didn't
actually remove it, even though we waited for it to finish.
This is mainly an issue resulting from not understanding that
docker containers remains "available" even though the job
running inside the docker container had exited.
We now remove containers that finish without timeout, but only
after having extracted the logs.
Otherwise, we would not be able to get the logs.
If a container times out, we stop the container before removing it.

fix for the too many open files problem

---

.vscode/settings.json
ci/docker.go
ci/docker_test.go
main.go

This commit fixes #319 (for real this time).
Now we create only one docker client when we start quickfeed,
instead of creating a separate docker client instance for each
job we want to run. This should hopefully save even more resources
and maybe some execution time for tests.
If this does not work correctly for some reason, we can revert to
the previous version, and instead make sure we close the client
between each job run. But that seems wasteful, and hence I wanted
to reuse the client across jobs. The way I understand the client,
it can still create, stop, get logs from and remove several
containers; that is, we shouldn't need a separate client for doing
these tasks.

another attempt at fixing the too many open file descriptors issue

---

ci/parse_script.go
ci/parse_script_test.go
ci/scripts/python-dat550.sh

This commit fixes an issue with docker image names listed
on the first line starting with #image/ where the image
name following after the inital / also contains slashes,
e.g. docker.io/eiriksak/school:dat550

Fix issue with docker image names with slashes

---

database/gormdb_assignment.go
public/src/pages/views/LabResultView.tsx
web/hooks/github.go

- fixes the issue where `SkipTests` status of an assignment would not update properly in the database
- hides the table with empty test results when displaying the build results for such assignments

Fix for submissions without automated tests

---

Makefile
public/package.json

This PR remove the necessity to install ui package globally and use the local installation (based on the package.json) in the makefile when building the ui.

Using local npm dependencies

---

ag/enrollment.go
ag/slipdays_test.go

Proposed implementation of UpdateSlipdays() including a graceperiod. 
The grace period is currently set to 2 hours. can and should be an int between [0,1,...,23].
This change can affect all assignments, that are not yet approved, on the currently running autograder service.
Currently doesn't support 1,5 hours grace-periods, using minutes instead grants this functionality.
`const gracePeriod time.Duration = time.Duration(90 * time.Minutes)`

UpdateSlipdays with a graceperiod

---

go.mod
go.sum

Updated golang.org/x/sys which caused go1.17 runtime to fail on our tests.

Fix test failure with go1.17

---

ag/assignments.go
ag/consts.go
ag/slipdays_test.go
assignments/assignments_parser.go
ci/results.go
ci/run_tests.go
web/courses.go
web/hooks/github.go

- Added `TimeLayout` in new file `ag/consts.go`.
- Replaced layout constants in `slipdays_tests.go` & `assignments.go`.

Fixing time.Parse layout constants

---

Makefile
ag/ag.proto

- Make target that outputs `ag.pb.swift` & `ag.grpc.swift` to the path specified in `proto-swift-path`.
- Adds an option in `ag.proto` to prevent generated Swift structures to be prefixed with `Ag_`.
Closes autograde/quickfeed-swiftui#75

Make target to compile ag.proto for Swift

---

ag/validation.go
envoy/envoy-test.yaml
main.go
public/src/index.tsx
public/src/managers/GRPCManager.ts
web/auth/auth.go

This PR introduces an updated envoy configuration that allows gRPC and regular HTTP communication to occur on a single port. This should remove the need for documentation introduced in #448 .
The PR also introduces basic authentication by session token.

Basic authentication & updated envoy config

---

assignments/assignments.go
ci/run_tests.go
web/autograder_service.go
web/courses.go
web/groups.go
web/hooks/github.go

This replaces %w and %s in error printing with %v. Printing with %w gives useless output.
%w should only be used to return errors for chaining via e.g., fmt.Errorf("... : %w", err).
This also replaces status.Errorf() with status.Error(), since none of our uses actually supplied a format string.
Fixes #455.

Replace %w and %s with %v for error logging

---

main.go
web/webserver.go

This removes the `script.path` command-line argument that has never been used in the code; the current implementation has a hardcoded `scriptPath` const. Ideally, we should implement #285 to allow course-dependent script paths, but that's for another PR.
Fixes #454.

Removed defunct script.path command line argument

---

doc/scripts/update.sh

Check if packet forwarding is enabled when updating (from the startup script).
We could also add checks from within main.go itself.
Fixes #471.

Packet forwarding enabled checked

---

database/db_user_test.go
database/gormdb_assignment_test.go
database/gormdb_group_test.go
database/gormdb_submission_test.go
database/gormdb_test.go
go.mod
go.sum
internal/test_helper.go
web/auth/auth_test.go
web/autograder_service.go
web/courses.go
web/courses_test.go
web/groups_test.go
web/submissions_test.go
web/users_test.go
web/util_test.go

- Added internal package with TestDB test helper
- Updated database pkg to use internal.TestDB() helper
- Service accept Database interface instead of *GormDB
- Replace util_test.go:setup() with internal.TestDB() helper
- Removed another instance of setup() test helper in web/auth
Fixes #478.

Internal package for test helpers; includes TestDB()

---

.vscode/settings.json
ci/docker_test.go
ci/parse_script_test.go
ci/run_tests.go
ci/run_tests_test.go
database/db_user_test.go
database/gormdb_assignment_test.go
database/gormdb_group_test.go
database/gormdb_submission_test.go
database/gormdb_test.go
internal/qtest/test_helper.go
web/auth/auth_test.go
web/courses_test.go
web/groups_test.go
web/submissions_test.go
web/users_test.go

- Moved internal.TestDB to internal/qtest
- Replace createFakeUser with internal/qtest.CreateFakeUser()
- Added CreatedNamedUser and EnrollStudent test helpers
- Added qtest.FakeProviderMap test helper
- Added qtest.RandomString(t) test helper
Fixes #481.

Internal package qtest with test helpers

---

main.go
web/webserver.go

This code hasn't been used since 2017 or so.
Fixes #386.

Remove fake provider command line flag and corresponding code

---

database/gormdb_repository.go
doc/dev.md
doc/templates/policy.md
kit/src/main/java/autograder/Score.java
public/index.html
public/package.json
public/src/components/forms/CourseForm.tsx
public/src/index.tsx
public/src/pages/HomePage.tsx
public/src/pages/views/HelpView.tsx
web/hooks/github.go
web/scm_helpers.go

We currently retain the Autograder moniker for code, since changes
to code may impact ongoing PRs and we want to avoid such changes at
this time.
Fixes #474.

Renamed Autograder to QuickFeed in doc (not code)

---

public/src/components/teacher/CourseGroup.tsx
public/src/pages/views/MemberView.tsx

When editing member and group lists we don't want to cancel, but we want to indicate that we are done editing.
Fixes #523.

Fixes button labels from Edit-Cancel to Edit-Done

---

kit/score/main_test.go
kit/score/panic_test.go
kit/score/score.go

This adds msg argument to `sc.Print()` and `sc.PanicHandler()` to allow a custom message to be printed in case of panic.
Fixes #537.

Added support for message to be printed when panic

---

kit/exercise/multiple_choice.go
kit/exercise/multiple_choice_test.go
kit/testdata/c-prog-questions-multiple-checked.md

This PR fixes an issue where multiple checked answers would count as correct if the first checked answer is the correct answer.
Examples that gave points:
```
Question 1:
Question 2:
```

Fixed multiple checked answers sometimes counting as correct

---

kit/score/results.go
kit/score/results_test.go
kit/score/totalscore_test.go

This fixes a rounding error discovered recently that would result in a score of 99 instead of 100, when all scores were equal to the max score.
Fixes #542.

Fixes rounding error in Results.Sum()

---

kit/score/main_test.go
kit/score/registry.go
kit/score/registry_test.go
kit/score/results.go

PrintTestInfo() will print tests in the order they appear in the
init() functions. There is no ordering across different init()
functions, so if multiple init() functions generate an undesirable
ordering of tests, those init() functions can be combined into one.
PrintTestInfo(sorted=true) will print all tests in sorted order.
Fixes #534.

Fix test ordering issue

---

ci/run_tests_test.go
database/db_user_test.go
database/gormdb.go
database/gormdb_assignment_test.go
database/gormdb_course.go
database/gormdb_group_test.go
database/gormdb_submission_test.go
database/gormdb_test.go
database/gormdb_user_test.go
internal/qtest/test_helper.go
web/grpc_auth_test.go

- Added test to show bug in access token course cache
- Fixed course access token cache issue
- Implemented improved token cache for courses
- Fixed error handling and added qtest.CreateCourse()
- Fixed CreateCourse to run as transaction
Fixes #574

Fix access token cache

---

.github/workflows/golangci-lint.yml
ag/assignment.go
ci/docker.go
ci/docker_test.go
ci/parse_script.go
ci/parse_script_test.go
ci/run_tests.go
ci/run_tests_test.go
ci/testdata/run.sh
doc/teacher.md
kit/score/results.go
kit/score/results_test.go
web/hooks/github.go
web/rebuild.go
web/rebuild_test.go

- Converted funcs to methods on RunData type
- Added run.sh script to testdata and load into Script
- Docker cleanup and simplification
- Cleanup Docker tests; added TestDockerPull
- Replace logger.Errorf with return fmt.Errorf
- Moved timeout code to separate method
- Separated RunTests and RecordResults
- Return pb.Submission from RecordResults
- Log notice about error not being a test failure
Fixes #588.

Refactored CI RunTests and RecordResults

---

scm/fake.go
scm/github.go
scm/gitlab.go
scm/helper.go
scm/scm.go
web/courses.go
web/webserver.go

This PR implements functionality to accept repository invites on behalf of a student when accepting their enrollment.
Currently it only accepts the invite to `<studentLogin>-labs`, but could easily add accepting invites for `info` and `assignments` as well. 
This functionality requires students to grant additional GitHub scopes, `repo:invite`

Accept repository invites on behalf of users

---

internal/qtest/test_helper.go
web/autograder_service.go
web/courses_test.go
web/groups.go
web/groups_name_test.go
web/groups_test.go
web/rebuild.go
web/rebuild_test.go
web/submissions_test.go
web/users_test.go

New rules:
- Group names can be no longer than 20 characters
- Group names can only contain letters, numbers and - and _
- As before only unique group names are allowed
This updates the backend to enforce these rules.
Fixes #345.
Fixes #546.

Prevent creating bad group names on backend

---

ag/assignment.go
ag/submission.go
ag/submission_test.go
ag/validation.go
web/courses.go
web/groups_test.go
web/submissions_test.go

- Trivial makeResults simplification; no need to append
- Use pb.SubmissionsForCourseRequest_ALL instead of default
- Make Assignment.CloneWithoutSubmissions robust
- Added ByUser and ByGroup predicate methods to Submission
- Typo
- Added TestGetSubmissionsByCourse
- Disabled output from TestDeleteGroup
- Refactor make{All|Individual|Group}Results functions
Fixes #621

Clean up make submission results functions used by GetSubmissionsByCourse

---

ag/submission.go
web/assignments.go
web/autograder_service.go
web/submissions_test.go

This PR fixes an issue where the `Release all` functionality did nothing (#604).
When a review is updated, the related submission and its score is only updated if the submission has been `released`. This means that unreleased submissions will have a score of 0. 
```go
if submission.Released {
// Updated review will most probably have a new score. Update the submission score as well
// for submissions with released review.
submission.Score = review.Score
if err := s.db.UpdateSubmission(submission); err != nil {
return nil, err
}
```
The release all functionality looks at *submission* scores, and releases all those above the given minimum score limit.
```go
func (db *GormDB) UpdateSubmissions(courseID uint64, query *pb.Submission) error {
return db.conn.
Model(query).
Where("assignment_id = …
```

Release approve all

---

.github/workflows/coverage.yml
.github/workflows/go.yml
.github/workflows/golangci-lint.yml
ci/ci.go
ci/clone_repositories.go
ci/consts.go
ci/docker.go
ci/docker_test.go
ci/parse_script.go
ci/parse_script_test.go
ci/run_tests.go
ci/testdata/run.sh
doc/teacher.md
doc/templates/dotnet-course/scripts/run.sh
doc/templates/go-course/scripts/run.sh
quickfeed.code-workspace

This obviates the need to use template variables in the `run.sh` script all together by replacing them with default environment variables (`$TESTS`, `$ASSIGNMENTS`, `$CURRENT`, `$QUICKFEED_SESSION_SECRET`) that can be used similarly. However, it avoids the additional complexity for users to understand how templates works (although it isn't too difficult, it adds another layer...)
Fixes #680.

Test runner script with environment variables

---

assignments/assignments.go
assignments/assignments_test.go
assignments/pull_requests_test.go
ci/clone_repositories.go
ci/run_tests_test.go
cmd/scm/main.go
internal/qtest/test_helper.go
scm/fetcher_test.go
scm/github_test.go
scm/scm.go
web/auth/auth.go
web/auth/scm_storage.go
web/hooks/github_test.go
web/hooks/push.go

This replaces the provider argument to NewSCMClient() with reading the SCM_PROVIDER environment variable.
Fixes #663.

Add support for SCM_PROVIDER env var

---

cmd/scm/main.go
internal/qtest/test_helper.go
scm/fake.go
scm/github.go
scm/gitlab.go
scm/scm.go
web/courses.go
web/courses_new.go
web/scm_helpers.go

- Renamed scm.Repository.WebURL field to HTMLURL
- Removed SSHURL because it is not used
- Removed HTTPURL field since is same as HTMLURL except .git
Fixes #654.

Renamed and removed fields in scm.Repository

---

internal/env/cert.go
internal/env/env_test.go
internal/env/scm.go
internal/qtest/test_helper.go
scm/scm.go

The currently supported variables have default values; it may also
be possible to return an error to signal that a var must be defined.

Improve support for env vars

---

scm/github.go
scm/github_test.go

Previously `scm.GetOrganization` would translate any err to `ErrNotMember`.
This isn't really changing anything except returning the actual error rather than assuming that the error is an `ErrNotMember`. It is unlikely that this fixes the problem in #565, but at least it should surface the real error in the future should it reappear.

Report real error from GetOrganization

---

cmd/envoy/envoy_config_gen.go
go.mod
go.sum
internal/env/env_test.go
internal/env/load.go

This replaces a dependency for loading .env files with a custom one. The idea is that this can also be used to load the .env file when deploying the quickfeed server. 
Note: this custom env.Load() function will not expand environment variables.

Add env.Load() to load .env file

---

scm/scm.go
web/scm_helpers.go

This prevents that a user-based SCM is used for other things than accepting repository invitations.
Fixes #709.

Add SCMInvite interface to limit exposure for user-only SCM clients

---

ci/docker.go
ci/parse_script.go
ci/parse_script_test.go
ci/run_tests.go
ci/run_tests_test.go

The BindDir and Dockerfile fields were not initialized in the parseTetsRunnerScript function, making it awkward to use in some cases, and causing a test failure in another.

Fix parseTestRunnerScript function to avoid test failure

---

doc/teacher.md
doc/templates/signup.md

This PR updates the signup documentation after the revised signup process with automatically accepting invitations on the user's behalf.
Added note about the invitation emails that can be ignored; there does not seem to be a solution to avoid these emails and thus closing #758 as there nothing that we can do.

Update signup documentation

---

internal/qtest/test_helper.go
web/auth/jwt.go
web/auth/jwt_test.go
web/auth/util.go
web/interceptor/access_control.go
web/interceptor/access_control_test.go
web/interceptor/auth_test.go
web/interceptor/helpers.go
web/interceptor/tokens.go
web/interceptor/tokens_test.go

- Removed interceptor and function inserting cookie into context
- Renamed `TokenString` func to `CookieString`
- Added generic function to insert cookie into request header
- Updated and slightly simplified TestUserVerifier
- Update access control tests to use `requestWithCookie`
- Update refresh tokens test to use `requestWithCookie`
- Update func call `TokenString(...)` -> `CookieString(...)`

Cookie passed in header rather than context

---

internal/qtest/test_helper.go
web/access_control.go
web/auth/consts.go
web/auth/jwt.go
web/interceptor/user_auth.go
web/quickfeed_service.go

We can simply pass along the UserID from the claims as a regular uint64 context value. This avoids doing database lookup for many cases where this wasn't needed and also avoids string parsing.
Fixes #735.

Remove getCurrentUser(ctx)

---

web/courses_test.go
web/groups_test.go
web/interceptor/user_auth_test.go
web/quickfeed_helper_test.go
web/repositories_test.go
web/submissions_test.go
web/users_test.go

- Removed unnecessary uses of fakeProvider
- Added MockQuickFeedClient to replace testQuickFeedService
- Removed TestGetRepo; was testing only internal func
- Updated TestUserVerifier to use MockQuickFeedServer
- Revised MockQuickFeedClient to accept interceptors
This is a partial fix for #791.

MockQuickFeedClient test helpers

---

web/hooks/pull_request.go
web/hooks/push.go

Fixes #837
- Moved handlePullRequestPush to pull_request.go
- Renamed sc to scmClient in handlePullRequestPush
- Renamed sc to scmClient in handlePush, runAssignmentTests
- Pass ctx and scmClient into handlePullRequestPush
- Pass ci.RunData to handlePullRequestPush

Move PullRequestPush handling to pull_request.go

---

web/stream/service.go

- Added the ability change the key type for the streams map
- Specify type of stream ID in tests
- Removed unused service
- Modified map based struct Service[T, V] -> Service[K, V]
- Update doc comment for `service.CloseBy()`
- Delete streams from service map when closing stream(s)

serivce.Close() and CloseBy() now use internalRemove()

---

assignments/assignments_test.go
assignments/tasks_test.go
ci/run_tests_clone_test.go
ci/run_tests_test.go
scm/env_helper.go
scm/fetcher_test.go
scm/github_test.go
scm/githubv4_test.go

Updating `scm.GetTestUser` to use access token and return a test username and test SCM client.
Resolves #856.

Update scm test helper.

---

internal/qtest/test_helper.go
web/interceptor/access_control_test.go
web/interceptor/tokens_test.go
web/interceptor/user_auth_test.go
web/quickfeed_helper_test.go
web/quickfeed_helper_web.go
web/thirdparty_auth_test.go
web/users_test.go

When mocking a client in a test we must ensure that shutdown(ctx)
is always called before a test ends; otherwise we may risk that a
failing test doesn't call shutdown(ctx), potentially triggering
another test to fail as well.
Fixes #861

Fix showdown in tests

---

scm/github.go
web/courses.go

There was one case where we only log an error and continue.
There was also on case that was missing a comment; we want to log
the error, but still want to continue with database updates.
Fixes #406

Fix missing error returns

---

scm/github.go
scm/mock.go
scm/mock_test.go
scm/scm.go

- removed unused scm method `GetTeam`
- split mock test for team methods into two separate tests for `CreateTeam` and `DeleteTeam`
Resolves #865.

Remove GetTeam

---

ci/run_tests.go
internal/qtest/mock_data.go
testdata/courses/qf104-2022/assignments/lab1/sequence/fibonacci.go
testdata/courses/qf104-2022/assignments/lab2/sequence/triangular.go
testdata/courses/qf104-2022/meling-labs/lab1/sequence/fibonacci.go
testdata/courses/qf104-2022/meling-labs/lab2/sequence/triangular.go
testdata/courses/qf104-2022/tests/lab1/sequence/fibonacci_ag_test.go
testdata/courses/qf104-2022/tests/lab1/sequence/main_test.go
testdata/courses/qf104-2022/tests/lab2/sequence/main_test.go
testdata/courses/qf104-2022/tests/lab2/sequence/triangular_ag_test.go
testdata/courses/qf104-2022/tests/scripts/Dockerfile
testdata/courses/qf104-2022/tests/scripts/run.sh
web/hooks/github.go
web/hooks/github_mock_test.go
web/hooks/github_test.go

This should prevent GitHub timeouts on webhook events, since it will start a new goroutine quickly and block if more than 5 push events arrive concurrently. The Handle() func should still return quickly to GitHub even though handling push events (running tests) takes a while.
Fixes #783

Support concurrent handling of push events

---

assignments/assignments.go
ci/ci.go
ci/docker.go
ci/docker_test.go
ci/parse_script.go
ci/run_tests_test.go
database/gormdb_course_test.go
qf/course.go

This fixes the issue with rebuilding dockerfiles on changes;
we basically remove an existing image and build it again.
That is, we rebuild the image when updating in the repository:
tests/scripts/Dockerfile
And when RunTests() is called on updates due to push events etc
we do not rebuild the image, but assume that it has already been
built or can be pulled from a remote repository.
Fixes #834

Fix rebuild from dockerfile on update in tests repo

---

internal/qtest/test_helper.go
web/courses_test.go
web/interceptor/access_control_test.go
web/interceptor/tokens_test.go
web/interceptor/user_auth_test.go
web/quickfeed_service.go

- Add test for UpdateCourseVisibility
- Update existing database enrollment rather than passed in enrollment
- Moved `RequestWithCookie` into `qtest`
- Update calls to `requestWithCookie` -> `qtest.RequestWithCookie`

Changed UpdateCourseVisibility

---

cmd/scm/main.go
scm/github.go
scm/mock.go
scm/mock_test.go
scm/scm.go

- removed unused scm methods `GetRepository`, `GetTeams`
- scm tool now uses `GithubSCM` instead of the general `SCM` client to enable access to GitHub API directly when necessary
Resolves #873.

Remove unused scm methods GetRepository and GetTeams, update scm tool

---

web/courses_test.go
web/interceptor/access_control_test.go
web/interceptor/tokens_test.go
web/interceptor/user_auth_test.go
web/quickfeed_helper_test.go
web/quickfeed_helper_web.go
web/thirdparty_auth_test.go
web/users_test.go

This fixes the MockClient to set up a httptest.Server that the client uses directly, avoiding issues with ListenAndServer() and Shutdown().
Fixes #877

Fix flaky tests that use MockClient

---

public/src/components/group/GroupForm.tsx

Enable teachers to see other teachers in group group form
This allows teachers to create groups among themselves for testing.
Fixes #328

Enable creating teacher groups

---

assignments/tasks_test.go
scm/github.go
scm/github_test.go
scm/helper.go
scm/mock.go
scm/mock_test.go
scm/scm.go
scm/scm_invite.go
scm/scm_options.go
web/courses.go
web/courses_test.go
web/groups_test.go
web/interceptor/tokens_test.go
web/quickfeed_service.go

SCM "options" types and corresponding `valid()` methods were defined in different places of the `scm` package. It made it easy to forget to update validators when introducing changes to the "options" interfaces. 
This PR puts validation methods close to the corresponding interface definitions. It also adds a missing validation check and updates the affected tests.
Closes #908.

Reorganize SCM validators

---

scm/github.go
scm/helper.go

Replacing `ErrMissingFields` in the `scm` package with simple error messages to reduce unnecessary complexity and improve maintainability. 
This PR is based on #909.
Resolves #910.

Remove scm error `ErrMissingFields`

---

scm/github.go
scm/helper.go
scm/mock.go
scm/mock_test.go

The default `allstudents` team serves no real purpose in the current system. However, it adds an extra call to GitHub API every time the status of enrollment changes. This PR removes this team and the corresponding steps in the enrollment process.
Resolves #897.

Remove `allstudents` team

---

web/auth/jwt_test.go
web/auth/jwt_update.go
web/interceptor/tokens_test.go
web/interceptor/user_auth.go

JWT manager's method `UpdateRequired` is now unexported.
Closes #812.

Un-export token update check

---

database/database.go
database/gormdb_submission.go
web/courses.go
web/quickfeed_service.go

This removes the unused argument courseID to the database method UpdateSubmissions (plural).
Fixes #924

Removes unused courseID argument in UpdateSubmissions database method

---

assignments/assignments.go
assignments/assignments_test.go
database/gormdb_assignment.go

Moved updateGradingCriteria to db.UpdateAssignments() and make use of transactions in UpdateAssignments().
Based on PR #950
Fixes #951

UpdateAssignments now use transactions

---

internal/env/cert.go

In some cases `net.LookupIP(domain)` would return a slice of IPs, for example:
```
127.0.1.1
154.X.X.X
```
where the first one is local, but the second is public. The current `IsLocal` would return `true` in this case, while we want it to return `false`.
The change introduced in this PR returns `false` if at least one IP is public, and `true` if not.

Minor fix for env.IsLocal

---

public/src/components/manual-grading/ReviewForm.tsx
public/src/overmind/namespaces/review/state.ts
public/src/overmind/state.tsx

This PR includes some fixes for manual grading in the frontend.
- Fetch reviewer from course enrollments (previously from `users`). Context: teachers that are not admins do not have access to the `GetUsers` endpoint. As a consequence, `users` will not be populated for non-admin teachers
- Fixed bug where `isAuthor` used review ID rather than reviewer ID

Fixes for manual grading

---

assignments/assignments_parser.go

We no longer support the `assignmentid` field in `assignment.yaml` files; users should use the `order` field to define the order number of an assignment. See the dat320 and dat520 courses for an example. @JosteinLindhom We just need to make sure that the dat310 course and possibly others don't use `assignmentid` before merging and using this code.

Removed deprecated yaml assignmentid field

---

cmd/approvelist/main.go
go.mod
go.sum
internal/qtest/test_helper.go
qf/qfconnect/quickfeed.connect.go
tools.go
web/courses_test.go
web/groups.go
web/groups_name_test.go
web/interceptor/access_control.go
web/interceptor/access_control_test.go
web/interceptor/metrics.go
web/interceptor/req_validation.go
web/interceptor/token_auth.go
web/interceptor/token_auth_client_interceptor.go
web/interceptor/tokens.go
web/interceptor/tokens_test.go
web/interceptor/user_auth.go
web/interceptor/user_auth_test.go
web/quickfeed_helper_test.go
web/quickfeed_helper_web.go
web/quickfeed_service.go
web/rebuild_test.go
web/scm_helpers.go
web/stream/stream.go
web/thirdparty_auth_test.go
web/users_test.go
web/webserver.go

This PR bumps `connect-go` version from v0.3.0 to v1.13.0.
As of 1.10.0 the `connect-go` project was moved to a [new organization](https://github.com/connectrpc).
Import paths have been updated for both `connect-go` and `protoc-gen-connect-go`. The QuickFeed Connect service has been regenerated using the newest version of `protoc-gen-connect-go`.

Migrate to connectrpc

---

internal/env/load.go

This fixes the bug due to go.work giving two root paths for the
modules (./ ./kit)
Fixes #1040

Fix bug due to go.work

---

web/groups.go
web/groups_name_test.go

This is an alternative fix that avoids adding another database method.
Fixes #1071

fix: prevent duplicate case insensitive group names

---

public/src/components/LabResultTable.tsx
public/src/components/submissions/SubmissionInfo.tsx
public/src/components/submissions/SubmissionScore.tsx
public/src/components/submissions/SubmissionScores.tsx

This change prevents the lab information from being squashed if a test name is very long.
It also prevents the lab view from being hidden at the bottom.
Closes #1054

Fix lab table squashing when test names are long

---

scm/github.go

Currently enrolling a student cause them to become an outside collaborator in a course organization. 
When a student at a later point creates a group, the student will be added to a GitHub team for the group. The student will then be invited to be a member of the organization. 
For the student to be able to access their group repository they have to accept this organization invite. In a not insignificant number of cases this invite expires (GitHub invites expire after 7 days), and teachers have to resend the invites manually.
This PR sets the student membership to `member` in the process of enrolling. The subsequent call to `acceptRepositoryInvites` will also accept the organization invite.
closes #1022

Set enrolling students' organization membership to `member`

---

public/src/components/navbar/Breadcrumbs.tsx
public/src/consts.ts
public/src/hooks/windowsSize.tsx
public/src/style.scss

This PR adds a windowSize hook that components can use to react to changes in screen height/width.
Our `Breadcrumbs` component now uses the hook to display the course code instead of course name on smaller screens.
https://github.com/quickfeed/quickfeed/assets/1346291/bfcad291-114e-4ba5-a8b6-1e184e103ab3
closes #1105

Navbar width fix

---

internal/qtest/mock_data.go
scm/github.go
scm/github_issues.go
scm/github_mock.go
scm/github_mock_opts.go
scm/github_mock_test.go
scm/helper.go
scm/manager_mock.go
scm/scm_errors.go
scm/scm_errors_test.go
web/courses_test.go
web/groups_name_test.go
web/groups_test.go
web/hooks/installation_test.go
web/interceptor/access_control_test.go
web/interceptor/tokens_test.go
web/interceptor/user_auth_test.go
web/quickfeed_mock_client.go
web/quickfeed_service.go
web/repositories_test.go
web/scm_helpers.go
web/users_test.go

This is aims to clean up the error messages and how errors are handled coming from the scm package.
The design is inspired by the upspin project's errors package, the Go 1.13 error wrapping, and Jay Conrod's blog about error handling guidelines.
This PR builds on #1093, which should be merged first before merging this one.
Fixes #571
Fixes #1113

Clean up SCM error messages and handling

---

assignments/tasks_test.go
cmd/scm/main.go
scm/github.go
scm/github_issues.go
scm/github_issues_mock_test.go
scm/github_mock_test.go
scm/github_test.go
scm/githubv4.go
scm/helper.go
scm/scm.go
scm/scm_options.go
web/courses_new.go
web/hooks/installation.go

- chore: rename SCM type fields `Path`, `Organization` to `Repo`, `Owner`, remove OrgID, Size
- chore: update GetRepositories method signature in SCM interface, implementation (qf.Organization -> string)
Fixes #1094 
Supersedes #1110

scm fields rename

---

ci/consts.go
ci/docker.go
ci/run_tests.go

This commit adds error handling for the case when an image is already being built for a job. It logs an error message and returns an `ErrConflict` error.

fix(ci): handle image conflict during build

---

qf/repo.go
web/hooks/push.go
web/hooks/push_test.go

This ignores push events on group repo's non-default branch. That is, unless the group repo has an associated pull request, in
which case we don't ignore the push event, and run tests and record the results.
Fixes #1053.

Ignore push on group repo's non-default branches

---

public/src/__tests__/ComponentsHelpers.test.ts
public/src/__tests__/mock_data/mockData.ts
public/src/components/ComponentsHelpers.ts
public/src/overmind/actions.tsx

- fix: refreshCourseSubmissions now fetches `ALL` submissions for enrollments
- feat(ui): the result view shows submissions for group labs for users not part of a group
Resolves #1047

Show submissions for group assignments where user not part of a group

---

ci/record_results.go
qf/assignment.go
qf/assignment_test.go
qf/submission.go

Fixes #1142
In addition, we replace IsApproved with a simpler function SubmissionStatus that ignore invalid submissions; instead we record such submissions in the database. That is, if a user submits to a group assignment or a group submits to a user assignment, we still record these results in the database, rather than ignoring them.
This also adds a recovery handler for catching a panic in RecordResult.

Fix nil pointer issue when recording results without previous submission

---

kit/go.mod
kit/go.sum
kit/sh/cmd.go
kit/sh/cmd_race_test.go
kit/sh/cmd_test.go

This is in preparation for releasing **QuickFeed's kit module release v0.11.0**.
RunRaceTest: changed from func(string, string) (string, bool) to func(func(*testing.T), string) (string, bool)
MustRun: added
RunCountTest: added

kit: add RunCounTest and more

---

.vscode/quickfeed-words.txt
ci/docker.go
ci/module_cache.go
ci/module_cache_test.go
doc/templates/go-course/scripts/Dockerfile-dat520
doc/templates/go-course/scripts/README.md

This adds hardcoded support for host-mounted go module cache.
The current implementation creates a folder for the module cache
in $HOME/quickfeed-go-mod-cache. We may consider making this a
configuration option in the future.
Fixes #1187

Feat: Support for hardcoded go module cache via host-mounted volume

---

cmd/anonymize/main.py

The `anonymize` script is no longer compatible with our current database schema.
The changes in this PR updates the SQL queries to match our current schema.
The script now also randomizes the submission commit hashes and user refresh tokens.

Update database anonymizer script

---

ci/record_results.go
ci/run_tests_clone_test.go
database/gormdb_tasks.go
database/gormdb_tasks_test.go
qf/group.go
qf/submission.go
web/manifest/manifest.go

Partially Resolves: #1202
RVV-B0012 was commited with SCT-A000, my bad.
GO-W1027 involved updating the `GetTasks` to return nil when tasks array is empty, and remove unnecessary initialization in `SynchronizeAssignmentTasks`
Codes for issues:
- SCT-A000: Possible hardcoded secrets detected in source code
- RVV-B0012: Unused parameter in function
- GO-W1027: Empty slice literal used to declare a variable
- GO-W1032: Use t.Setenv and friends instead of os.Setenv for test file(s)
- GO-W1029: Usage of both value and pointer receivers

Deepsource, backend and secret issues, 16 in total.

---

.vscode/quickfeed-words.txt
go.mod
go.sum
internal/reload/watcher.go
internal/reload/watcher_test.go
main.go
public/src/index.tsx
web/server.go

This PR adds live reloading of the browser if changes are detected in the given folder (`/public/dist` in this case).
If QuickFeed starts in -dev mode, we add an endpoint `/watch` that the frontend can connect to. If a file change is detected, the server sends a message to the frontend client, which triggers a reload.
To activate this functionality the server has to run in development mode, and the frontend must be compiled in development mode.

feat: add file watcher for live-reloading in development environment

---

.vscode/quickfeed-words.txt
doc/docker.md
doc/scripts/setup-docker-group.sh

Resolves #518
This PR contains a script for linux,  WSL (windows) or mac without docker desktop. It configures a docker group which Docker use to determine if a user has access.
[As mentioned](https://github.com/quickfeed/quickfeed/issues/518#issuecomment-2627684935), does docker desktop bypass the permission issue.

Add script for creating docker group and update related docker docs,

---

internal/env/auth_secret.go
main.go
web/manifest/manifest.go

The case of wanting to both create a new github app and generate a secret was restricted because the modification of the env variable `QUICKFEED_AUTH_SECRET` with the save function creates the backup file: `.env.bak`, happens before creating the app.
The restriction of creating an app when the `.env.bak` file exists is intentional, as Hein mentioned in the related issue. But is in this case problematic since when a user wants to create a new app with a new secret its not possible because the secret generation occurs before the instance of creating the app.
The secret is required to be generated before the [NewTokenManager](https://github.com/quickfeed/quickfeed/blob/master/main.go#L117), because it is used when creating the [Token …

Make `new` and `secret` flags compatible

---

assignments/assignments.go
qf/course.go
qf/course_test.go

This implementation is quite complex. The courseMutexMap is stored in memory, on the heap and updated with the mapMu mutex since it will be accessed concurrently. The unlock method is questionable because it does not handle the case of the mutex not existing, but this will be considered as a developer mistake. Lock should always be called before unlock.
Closes: #818

Add mutex for each course rather then using a common update mutex

---

cmd/approvelist/main.go
qf/enrollment.go
qf/submission_test.go
web/courses.go

Closes: #1155 
- Rename CountApprovedSubmissions to UpdateTotalApproved
- Remove unnecessary total approved counter
- Simplify and merge if statements
Im not sure if reseting the `m.TotalApproved` to `0` in the beginning of the method is necessary. I couldn't quite understand if this method is only called with the value as zero or not. Previously it was overwritten by a separate counter variable, which I think is redundant, the increments can be done directly.
I switched out the struct map with a bool map to merge the if statements. Im not sure if this type of mapping is buggy, but the tests pass and there aren't any compling or runtime errors.

chore: Remove LastActivityDate and rename CountApprovedSubmissions to UpdateTotalApproved and 

---

assignments/testdata/tests/scripts/Dockerfile
ci/testdata/Dockerfile
doc/templates/go-course/scripts/Dockerfile
testdata/courses/qf104-2022/tests/scripts/Dockerfile

Closes #1247
I don't know how to solve [Pin versions in apk add DOK-DL3018](https://app.deepsource.com/gh/quickfeed/quickfeed/issue/DOK-DL3018/occurrences?listindex=0), because I get this type of error when setting specific versions:
```bash
ERROR: unable to select packages:
git-2.40.4-r0:
breaks: world[git~2.4]
```
You can ignore it, but thats just annoying as well. I recommend just removing this from DeepSource by [ignoring it on DeepSoruce](https://docs.deepsource.com/docs/repository-view-issues#ignore-issues-in-files)

DeepSource(Docker): Resolve bug risk issues

---

.env-template
doc/deploy.md
internal/env/cert.go
main.go
web/manifest/manifest.go
web/manifest/manifest_test.go
web/server.go

Closes: #1195 
The baseUrl for the redirect url on `master branch` does not include the http address. I made a simple method which combines the domain and the http address. Default callback url will thereby be: `https://localhost:443/auth/callback/` which is the same as `https://localhost/auth/callback/`
`https://uis.itest.run/` runs on the default https port and the port is therefore hidden. If you add the port `443` and enter the url: `https://uis.itest.run:443/`, will the port number be removed. Attempting to connect on a different port will fail unless Quickfeed is active there as well.
A user of Quickfeed can now specify their own port to run the Quickfeed server on, the default port is 443, and you can possibly ignore the port when its the default https port, but doing so will most …

Resolve http.addr bug and replace http.addr flag with env variable PORT

---

public/src/components/Groups.tsx

Closes: #1283
Im not sure why DeepSource thinks this is deeply nested:

Wrap ths inside of a "tr" element, to prevent HTML error in console

---

assignments/pull_requests.go
assignments/pull_requests_test.go

Fixes: #1231 
@meling No, I don't want to write a test for AssignReviewers. The code written is quite confusing and suprisingly complex for the given functionality (Update: Im refering to getNextReviewer), plus is this code even used? 
AssignReviewers call hierachy:
Only called here, in `handlePullRequestPush`
```go
if taskSum >= scoreLimit && !pullRequest.HasReviewers() {
wh.logger.Debugf("Assigning reviewers to pull request #%d, in repository: %s", prNumber, repoName)
if err := assignments.AssignReviewers(ctx, scmClient, wh.db, rd.Course, rd.Repo, pullRequest); err != nil {
wh.logger.Errorf("Failed to assign reviewers to pull request: %v", err)
return
}
}
```

getNextReviewer - Resolve potential panic

---

.vscode/launch.json

A launch profile is very useful for debugging, as it allows for developers to view the workflow and analyze different sections while the program is running. This is much more reliable and efficient than printing in-memory values to the console or the standard output.
"Launch Quickfeed" will let developers start Quickfeed in debug mode for both frontend and backend, which can in the future be combined with the Docker container, if that is diserable.
A user can run Quickfeed either directly or through the created binary or executable.

Add helpful launch profiles for debugging

---

internal/ui/esbuild.go

The watcher doesn't like that the dist folder is cleaned and not populated with files at the same time. I think it closes prematurely because the dist folder appears to be empty.
Update: `resetDistFolder` was previously removing the dist folder instead of cleaning up the old files. The watcher weren't capable of tracking any changes because of this.

Resolve Watcher and Esbuild Reset Plugin compatibility issue

---

database/gormdb_submission.go
database/gormdb_submission_test.go

Closes: #1278 
Setting the release to false is now reflected in the database. This was done with GORM solution: https://github.com/quickfeed/quickfeed/issues/569#issuecomment-1013729572

Database - UpdateSubmission; Convert to select query

---

internal/env/save.go

This removes any whitespace (blank lines) before and after the content of .env files.
Fixes #1362

Remove extra whitespace in .env file

---

public/src/components/Lab.tsx

Using the index as key should be fine in this specific instance as the build log is static,
i.e. users cannot modify it in any way.

Fix potential duplicate react key in list

---

public/src/pages/CoursePage.tsx

useLayoutEffect takes the sidebar and main page into consideration when loading the page and prevents it.
Closes: #1282

Prevent the sidebar from moving in front of the page.

---

public/src/components/Members.tsx

Resolves: #1289 
This is a different solution from the planned one in the related issue, but I kinda like it and it was a very minimal change. Only downside is maybe the width on large screens, but you atleast won't make people with a small screen frustrated.
Before:
After:
Can optionally reduce it to 75% width and aligned to the left;
Only need to add: "div className="w-75" inside of <> and in the end add a close tag for the div: `</div>`

Adjust members page to be displayed over the whole page
